#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2022/03/03 05:43:34
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?dataset_id=cmip5.output1.NCC.NorESM1-M.historical.6hr.atmos.6hrLev.r1i1p1.v20110901|esgf-data1.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?dataset_id=cmip5.output1.NCC.NorESM1-M.historical.6hr.atmos.6hrLev.r1i1p1.v20110901|esgf-data1.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1985010100-1985063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1985010100-1985063018.nc' 'SHA256' 'ae62bcf582ad76441d425f45ac2e0247bcf56467d4b7fd547349bed005abfabc'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1985070100-1985123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1985070100-1985123118.nc' 'SHA256' 'd2efb0e1af41fdf1771944c7c02265e3303fc2aa04d018f7bebb17d89eb1f42d'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1986010100-1986063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1986010100-1986063018.nc' 'SHA256' '3fc2981bb730bc8cc075903b7d656bc34742d4dce101888389dcea40c1d8edb3'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1986070100-1986123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1986070100-1986123118.nc' 'SHA256' '7ffad1933e89e3fe7d6e0cf8aad85601e0af8f1477308f73b7601265905fd611'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1987010100-1987063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1987010100-1987063018.nc' 'SHA256' '673976febcbba86a315b5d440a5d4b1db15c35689df523696e848f284a5d043e'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1987070100-1987123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1987070100-1987123118.nc' 'SHA256' 'c5d86cfce450e01dd0d422d4875b0695d446a36417a0e0b21e5be229eef3498c'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1988010100-1988063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1988010100-1988063018.nc' 'SHA256' '4b097e60b8b005074756dff91a3be2e4cd41104bb795d896d99b713a07df1b22'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1988070100-1988123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1988070100-1988123118.nc' 'SHA256' 'db861ed03d7c8c0dd82ff1098d5240723e0dd0e82d77275cc2ab461736c80597'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1989010100-1989063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1989010100-1989063018.nc' 'SHA256' '4b5656038e02428d13f6eab474eea9c59a00b6f1afa4507f1200871b913be914'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1989070100-1989123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1989070100-1989123118.nc' 'SHA256' '7768ca390e7771d080f9881c14072e2949a9ab8814521f0c4bb1b28d52c08a2a'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1990010100-1990063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1990010100-1990063018.nc' 'SHA256' '6bc0c73fd1a37013083bf8d2a655abf5f1013680fe61ca40899fce3622849131'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1990070100-1990123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1990070100-1990123118.nc' 'SHA256' '16b7536571c9fbdd6801d05e3ffd7e1c88f1bc933c2699bdc381515db8663662'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1991010100-1991063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1991010100-1991063018.nc' 'SHA256' 'd7db837ae4d3d8984f4d51bc0264f549d0f1ca93fbe3d41644b7b9a89ba28216'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1991070100-1991123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1991070100-1991123118.nc' 'SHA256' '19a9420fd754cdfa3e2bd9dc8689f586cd91b8cfa97a6a0cbe5b84fcdbb7731e'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1992010100-1992063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1992010100-1992063018.nc' 'SHA256' '80243f85eaa484fc4c22fb5d95f42c0f27822fda9e382b7685f7336bc3a145fe'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1992070100-1992123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1992070100-1992123118.nc' 'SHA256' 'e4034a25f4d981037ed748e7e0dbfb04194d03a24fb889e300c13612e2da3ebe'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1993010100-1993063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1993010100-1993063018.nc' 'SHA256' 'f1fd6a4526f42ae5703c10cce6aff0c3cb6fc0f670bb1ca4eed38909e5e191a4'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1993070100-1993123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1993070100-1993123118.nc' 'SHA256' 'ff4b08730017b9e0bfd0dbf9675a61fabecae445bf9c5ef209d35bb1b7df39e9'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1994010100-1994063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1994010100-1994063018.nc' 'SHA256' 'ae3b61f3b385fdecb7914cc398e9017d8143f581241e277be33b2f4fa561b527'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1994070100-1994123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1994070100-1994123118.nc' 'SHA256' 'c097c0cecce93648d4316763338ba9039cc7ea244d5cb6812904ee09e7e79baa'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1995010100-1995063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1995010100-1995063018.nc' 'SHA256' 'f1b7f5d2ddfaf3284174f199aa642fbeb7db2cc560aa0690d2c8a74639f7c2c8'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1995070100-1995123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1995070100-1995123118.nc' 'SHA256' 'dc57bc0ef0e487fcf19e68b7559ea4c7b8d926f20486183766b42a6d2ccc25a3'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1996010100-1996063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1996010100-1996063018.nc' 'SHA256' '7176348f03234a24dc36e639515e6c9cd710b7daa10314a19eba8e0c9df0c42b'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1996070100-1996123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1996070100-1996123118.nc' 'SHA256' '3acaa0e7472e1bbdb5cc689e31d9a805fcb532bce90842641d66ed878dd42faf'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1997010100-1997063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1997010100-1997063018.nc' 'SHA256' '6e1d8e43814920e7279820e4d51a26eba94003adc3e87eecbe17ba42f14aa506'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1997070100-1997123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1997070100-1997123118.nc' 'SHA256' 'ceee5419a4a350435171c136fdc0b275a71b14a0e531f6af65ae7e91c554192f'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1998010100-1998063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1998010100-1998063018.nc' 'SHA256' '778a3f566f07a17158c3eb45c05214e4a15bcfcb132a372e547a4100f23f8190'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1998070100-1998123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1998070100-1998123118.nc' 'SHA256' '11ae1991ad86230c05989c85f9fc30bb369d1bdadd0ec430448be54c2748dd35'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1999010100-1999063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1999010100-1999063018.nc' 'SHA256' '9d1c7fdfcd218020c167fb3f73ce03cb5cb9c30250d91eb74cd0209e1590e32f'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_1999070100-1999123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_1999070100-1999123118.nc' 'SHA256' '0a972c15cc4d4bd31aa624c8c3452e646e27cf008b4210c410bd277dcb38872c'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2000010100-2000063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2000010100-2000063018.nc' 'SHA256' '2319f8ca1ec3c9ed5a17457f62144442af30a98f50b35800f1a59bdc87caf89a'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2000070100-2000123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2000070100-2000123118.nc' 'SHA256' '0328e6e38e899439f5a8412307edd9c09c313c276bcf617ec78a992ec4a2e451'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2001010100-2001063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2001010100-2001063018.nc' 'SHA256' '1a7610adf70ca3a829f5e9646984acc1274065945926d0824727d73bd7d1fbc3'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2001070100-2001123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2001070100-2001123118.nc' 'SHA256' '0717217946f220c9565bb40309e42a4f41fb20d9137d4e4a71f47291107a4464'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2002010100-2002063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2002010100-2002063018.nc' 'SHA256' '64c07241575f45c4644804032daf2a4356072f7a5d8df4268d5716125733e5e0'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2002070100-2002123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2002070100-2002123118.nc' 'SHA256' 'd8a4a8c4fff56f162347d95f01ccd6ad9c61c7bacc0b8e741e8e16c6780b60ad'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2003010100-2003063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2003010100-2003063018.nc' 'SHA256' '685cdf6d00c14bc5692884e7d764be8326dd2af3ee76b5170ca236e3e99cfb10'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2003070100-2003123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2003070100-2003123118.nc' 'SHA256' '635dcb008be6f495b4c35c1df1d5b7c5216f8b66d60971873ae18b11d4546d8d'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2004010100-2004063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2004010100-2004063018.nc' 'SHA256' '117256fb2a3050a15d7679ab932eb60fbc4f4ea76278d8b0a09b7bc63947c1cf'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2004070100-2004123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2004070100-2004123118.nc' 'SHA256' '0c506e2edc129a0415519adb14edb21ea157442f18bcc89270a4c00aba47cdfd'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2005010100-2005063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2005010100-2005063018.nc' 'SHA256' '21102953b8cf0e06536bba34c0f274f48839c65935677451da14ad1dd925309f'
'ua_6hrLev_NorESM1-M_historical_r1i1p1_2005070100-2005123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_historical_r1i1p1_2005070100-2005123118.nc' 'SHA256' '6ad5a9102115ef0b82e530bc46bc76f76d3bcc2981fee4f00869648644384e1f'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1985010100-1985063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1985010100-1985063018.nc' 'SHA256' 'c69facef5144bdf44bd56fb2f9abe70e9b0a01a49320e3c7a1a4127129b991b5'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1985070100-1985123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1985070100-1985123118.nc' 'SHA256' 'ac31eb6c632cd9ef495f9422256ac3b26fbd7c07b042ce1fb3a623b095f6cbd7'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1986010100-1986063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1986010100-1986063018.nc' 'SHA256' 'eeac46f6ea6ba674324138f87cb07b46f7260e43d1f7b6db7e1284720290a000'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1986070100-1986123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1986070100-1986123118.nc' 'SHA256' 'd9cc8e267af3d3dda589bf8ccd8341dc38c112c34abdb3160fe223beb7ca889a'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1987010100-1987063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1987010100-1987063018.nc' 'SHA256' '520d5198dbcbf1d3b9652ac1eeb8678152dfa1a3f340b27f2ee1ab4dc0900ca1'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1987070100-1987123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1987070100-1987123118.nc' 'SHA256' 'a8e8953110aa1e0afa4af982b04f1b450f722cee7c110382285288cb55c48885'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1988010100-1988063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1988010100-1988063018.nc' 'SHA256' 'f704a6cfda3fd7c9eeab6d73bf4b0790865dc5cbde77c55de5b6205bebdb376c'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1988070100-1988123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1988070100-1988123118.nc' 'SHA256' '8de808c65c3c6e2938f3d60d682f2584c4cc8181b39b15e76b9cda7dd48e35f9'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1989010100-1989063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1989010100-1989063018.nc' 'SHA256' 'f2079a7e1eeee6f173a19499b9b5cc28283105251d52cedecd03602f1e7ff77f'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1989070100-1989123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1989070100-1989123118.nc' 'SHA256' '7fb85d091c1ccd1d5ddcdc6fdedcb3cc2cd5fcfabdd0a5c0b4fb11de78046d6f'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1990010100-1990063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1990010100-1990063018.nc' 'SHA256' 'd83593c22372420b3f17b427d454c1119e917fcee6f58a5854876370bf47f6cc'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1990070100-1990123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1990070100-1990123118.nc' 'SHA256' 'f3f727031aa6d57991e46e73660a5625d416169f57ccc376f98c370e91a4ec52'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1991010100-1991063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1991010100-1991063018.nc' 'SHA256' 'be3ae36e8912160fc7eb80a939f9447e9622f6c96d0d0a173b19f0ba2a3ef03d'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1991070100-1991123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1991070100-1991123118.nc' 'SHA256' 'a51768e6b2a723f41cfcadead02b92d14d67c1fa5e30946d78b67fcdb290464e'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1992010100-1992063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1992010100-1992063018.nc' 'SHA256' '57632d0a9ae8031639d2920bc10805b6c764ad2825e8fbbd5f5a7f7fc016f7fb'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1992070100-1992123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1992070100-1992123118.nc' 'SHA256' '8c80e5e0ecfad91be20b263e9d562eb23d7d8971879c685645d429a96fab32ae'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1993010100-1993063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1993010100-1993063018.nc' 'SHA256' 'a063b3ae4e7e2392aaeb85d53a9fae64cf651dd074a78d4813ff1767aa807a22'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1993070100-1993123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1993070100-1993123118.nc' 'SHA256' '71891b9deebfae8c3e7afcd800fd0fac481a57009ae4c2794902a184d2be1151'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1994010100-1994063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1994010100-1994063018.nc' 'SHA256' 'bb243364c7f6152afb0c67a242e994486a3f259b03c3103dd596cbaf771f913f'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1994070100-1994123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1994070100-1994123118.nc' 'SHA256' 'd82f69872f3e6d2dc36d527692e3d61fc8dc9a7c48a5430e21dd6e2515a704d3'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1995010100-1995063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1995010100-1995063018.nc' 'SHA256' '77a62d291bc144d79ff67161b165e4460ce312d8522d4d681da96b8415f0cbb0'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1995070100-1995123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1995070100-1995123118.nc' 'SHA256' '63c048a8f5f96f38c9373660a982ef520ec9a0a466e7b428032e3c31ad8b9212'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1996010100-1996063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1996010100-1996063018.nc' 'SHA256' '42a98bd8792916c858e07f68e9767c54d113bcf9f90667ad7c8f45e314319851'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1996070100-1996123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1996070100-1996123118.nc' 'SHA256' '7fb1f9fda2cf3ed1ee8bb572b4fc9749b6c9593508dd4f83ecc76429ed122cd8'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1997010100-1997063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1997010100-1997063018.nc' 'SHA256' '21eecb30ce7928bda0bdcf0517bf0785b37e78351c8c0aa0a42414bc8292f957'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1997070100-1997123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1997070100-1997123118.nc' 'SHA256' '8777799f2d543f9deb372840b584bd8e4a9e27da535ccd8a9fd453f86b1fb304'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1998010100-1998063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1998010100-1998063018.nc' 'SHA256' '670e74320aed20e2d7125b75200ef585c737ae701aa8a52390652a363c72a0c4'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1998070100-1998123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1998070100-1998123118.nc' 'SHA256' '21699a9c0b46033c76b05ea7e0ac04389700b457850be59851a98fff27c6812a'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1999010100-1999063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1999010100-1999063018.nc' 'SHA256' 'afaf020c59a00963dd7f963e36a64a7d2292a0e81e64b88ed49caf8eb42d29f8'
'va_6hrLev_NorESM1-M_historical_r1i1p1_1999070100-1999123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_1999070100-1999123118.nc' 'SHA256' 'b9d5421f39f6b50b81f77f3dea6a1ae2fbab76837db919031413bd61a8c13847'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2000010100-2000063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2000010100-2000063018.nc' 'SHA256' '40065afbda4f0b56c3a85d3e689f7bdec10cf7482434ac14be229a14517434ef'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2000070100-2000123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2000070100-2000123118.nc' 'SHA256' 'b921bf01499d700ad96b76468e344266f9d7cd70e688896f310d7d90d50ef0fe'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2001010100-2001063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2001010100-2001063018.nc' 'SHA256' '716e904d7c72c25d2c3f6af969de3265d602a5d0cd873d7e203273f859c49143'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2001070100-2001123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2001070100-2001123118.nc' 'SHA256' 'b876449273bfb2621b4caef27222f375bb54ae7e2d3c97249f0074e52c02a4da'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2002010100-2002063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2002010100-2002063018.nc' 'SHA256' 'a1304e26f905f1c32a964677b0a7bea80485f1c39d39bc15c8f22b1bea01bd97'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2002070100-2002123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2002070100-2002123118.nc' 'SHA256' '830e3b1b57ec75c95d8e3127a3444f34d54e355e141a30b307a5e2006ac88f07'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2003010100-2003063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2003010100-2003063018.nc' 'SHA256' '59cbc602e809216bc1a5602e578283c6fea94bb8cf3591a2205558d25ad724c4'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2003070100-2003123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2003070100-2003123118.nc' 'SHA256' '99f7dc4cca870e129e678682f6b46dd38649c404e2ad14ae8a5b418eb4c6526c'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2004010100-2004063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2004010100-2004063018.nc' 'SHA256' '2c5e1e7b1bbfaa92eaca32c3fd59c8cbda0400edc65aaf34cb773c647de77126'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2004070100-2004123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2004070100-2004123118.nc' 'SHA256' '399f694fcc11de5bf2f8dd99fc44ec578f6290d7d554f907a7ce7a03075b2521'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2005010100-2005063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2005010100-2005063018.nc' 'SHA256' '7f0dc7aff65f5da64759f3ac8055f17509cd15fe8cf4ad633a83622a768334d7'
'va_6hrLev_NorESM1-M_historical_r1i1p1_2005070100-2005123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/historical/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_historical_r1i1p1_2005070100-2005123118.nc' 'SHA256' '4504a62c5643901c1d89a2b65c6f0623df7a2347bb0359efdf8838eb4a1d5a54'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 454 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
