#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2022/03/03 05:43:39
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?dataset_id=cmip5.output1.NCC.NorESM1-M.rcp26.6hr.atmos.6hrLev.r1i1p1.v20110901|esgf-data1.ceda.ac.uk
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?dataset_id=cmip5.output1.NCC.NorESM1-M.rcp26.6hr.atmos.6hrLev.r1i1p1.v20110901|esgf-data1.ceda.ac.uk'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2080010100-2080063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2080010100-2080063018.nc' 'SHA256' '6e4d4733556cc60c65752baabe82cea2da85c79fedfc950b7c3c32b59f1590fe'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2080070100-2080123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2080070100-2080123118.nc' 'SHA256' '7e74567a9d51a2e856edb31050181d8d04494a9924fabd5caed840c4a3187d2b'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2081010100-2081063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2081010100-2081063018.nc' 'SHA256' 'ec2b848ba9582ce12ff96121cdc682c9e9404930da7bfec5f7e6e274dc788fa6'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2081070100-2081123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2081070100-2081123118.nc' 'SHA256' '1b16b3f0934d71829f0422f650299902a71eb57dad35270d0874b09d60d404a5'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2082010100-2082063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2082010100-2082063018.nc' 'SHA256' '30c806758758c02df5306a734ebb10397d4e68400445916d6174e4e0abf85705'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2082070100-2082123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2082070100-2082123118.nc' 'SHA256' 'ec66ffee18165f80d1211328c95506c13500d00eea97449797296d122fcb7e62'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2083010100-2083063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2083010100-2083063018.nc' 'SHA256' '859a1281c9dc53ccf436322f415043937ed4de10e934f1938c44f5ed7b0fc394'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2083070100-2083123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2083070100-2083123118.nc' 'SHA256' '019a5f5bd3bbe7eb65710bd0379694cc2154f50adf1c5f3811ebcb36d51ca463'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2084010100-2084063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2084010100-2084063018.nc' 'SHA256' '8534b796ac616d0eefea845ca9d5d1ab8a46f06ade5ff65066234e4e81630877'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2084070100-2084123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2084070100-2084123118.nc' 'SHA256' '10e680230dc096ec00575e375abdedefc1839755dcb3f27e0b35230bdc7c6aa8'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2085010100-2085063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2085010100-2085063018.nc' 'SHA256' 'b0911e0369176f0ffcf8126b9b8462fcc568244b4562ca52a7a59828ad94fc1d'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2085070100-2085123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2085070100-2085123118.nc' 'SHA256' 'bca98d2a8c774aee002d98524b9f73907725d80f4bc29cdaa7bfa69792ddadaa'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2086010100-2086063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2086010100-2086063018.nc' 'SHA256' '2f050996069df64afed7c9368f8a40adff6339f1b1941b6119815867a7973607'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2086070100-2086123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2086070100-2086123118.nc' 'SHA256' '96eaa86b92042da9bb9677e7374805568d1cdd0192dddcf262bee2a3176844b0'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2087010100-2087063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2087010100-2087063018.nc' 'SHA256' '8c278658533668690a654b47be4093a98d0c363aa1443cd1634c02164ed722fa'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2087070100-2087123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2087070100-2087123118.nc' 'SHA256' '4c9e56269f4ce49a6416aeaad63029489cd76ba28eb3426cfbaaf65a1384c053'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2088010100-2088063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2088010100-2088063018.nc' 'SHA256' '0fbf5cffff46bbdb8255ef08ada2ed52aba87e7a384425887e5d734e38d6149b'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2088070100-2088123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2088070100-2088123118.nc' 'SHA256' 'eb955f9d0f18c956b0635ba16177f401ec484c6e8b8174b98c895755199669b3'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2089010100-2089063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2089010100-2089063018.nc' 'SHA256' '00bc416e23cfc1c34e9c6311d9debf9dd06d9da6b30bb03e34e929df2bb0ced6'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2089070100-2089123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2089070100-2089123118.nc' 'SHA256' '18704a0c10464b0e012ba04d78190fc4e4fdaca31bdd7797ef8bb2fcb276d121'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2090010100-2090063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2090010100-2090063018.nc' 'SHA256' 'fd1c67d66cdcb79fd30d527f22e16336daed1392f25459b51df46487b6fcffe7'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2090070100-2090123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2090070100-2090123118.nc' 'SHA256' 'ad87240eb0b856514593e90117d415de6e6b30f524e5fad18c5a6525329e89a5'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2091010100-2091063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2091010100-2091063018.nc' 'SHA256' 'c2a1097182abac21e34dfafc19dbc327d667e3cc73815c3add1b73d059b33919'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2091070100-2091123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2091070100-2091123118.nc' 'SHA256' '3ced67d1bdda537025ef5f4a2078f795be0ffcf3a10101ceba196bef75b099eb'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2092010100-2092063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2092010100-2092063018.nc' 'SHA256' '73be1ae16c250eb2a9904c21e225240aebe68b4410c5abfc4bccc74d4cc3b790'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2092070100-2092123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2092070100-2092123118.nc' 'SHA256' '00fd1009e345d5ec468e941ca1d15253ec91f817c057d1b3e9c5f7acdd7d96cf'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2093010100-2093063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2093010100-2093063018.nc' 'SHA256' '9c1cef24afb554e4c355ee4b553cdc166b8357d629997d3928493228813329d9'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2093070100-2093123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2093070100-2093123118.nc' 'SHA256' '8de7408e82ca11b43ade05ca188e48af48a94bc416a38b7ad8a4626278246086'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2094010100-2094063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2094010100-2094063018.nc' 'SHA256' '2b81900dd4967e9f5cea36893bb43fbf0fca5f6ab1132739d3159ba87b2b7ddd'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2094070100-2094123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2094070100-2094123118.nc' 'SHA256' '443f78372d884355ee4e95b998f2f9d455f5c333153e6be4c2fc457c3a7878d8'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2095010100-2095063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2095010100-2095063018.nc' 'SHA256' 'c2801096744cd88d0ff825ca8ee2aa355253bfa1a1a99a5c93cdea0f5d39ab4b'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2095070100-2095123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2095070100-2095123118.nc' 'SHA256' 'ae29ad833a53d6d8cc7958e3b7f5e87b4943d190be3f1e7af027318ed151f8cf'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2096010100-2096063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2096010100-2096063018.nc' 'SHA256' '3126057c65402a29830ab0cb4590cc28d529d99eb2629bf542513e377632f8b5'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2096070100-2096123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2096070100-2096123118.nc' 'SHA256' '559f7dde1af2a3360fd81cfe0126ae1e3ef2183af2abd2bf446632e7d0891355'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2097010100-2097063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2097010100-2097063018.nc' 'SHA256' '2e3a800b9128497ab511866c2522ba3bfa737e61c18445fc9e69de2ab559d116'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2097070100-2097123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2097070100-2097123118.nc' 'SHA256' '945da8d1c76300699c40106a20a7d60841b9769a085358775d44fd6df0649c8e'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2098010100-2098063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2098010100-2098063018.nc' 'SHA256' '2de8703c5076b2831908798fc32b26252cb647c09285ed012020c5e85c4755d8'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2098070100-2098123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2098070100-2098123118.nc' 'SHA256' '9729f0fdaabe6b7b9dfd9d0f75b19f29249baa94451dcff0459fd6cb02a279c4'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2099010100-2099063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2099010100-2099063018.nc' 'SHA256' 'd0ff2ffc843bc35cf43e29b93a7c81450b1ca031521e7213a365afa9c2f0f1fb'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2099070100-2099123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2099070100-2099123118.nc' 'SHA256' '81c11da4e83c515f8c2ec0e0099912920d46761469d46a8c4dd6f63ddde26808'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2100010100-2100063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2100010100-2100063018.nc' 'SHA256' '013eef07f750f37cf55e5c6e66d6540223f32dc340c45ec27f5dc9c5bcf67f09'
'ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2100070100-2100123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/ua/ua_6hrLev_NorESM1-M_rcp26_r1i1p1_2100070100-2100123118.nc' 'SHA256' 'd40247aa6a06e9b7babe24bef11096d5e657c6d0a257a9812ffe70a368f89197'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2080010100-2080063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2080010100-2080063018.nc' 'SHA256' 'a7fe2ba11d1139a638fb7cdcf8fe4fafa8196e7ff2c438da388e01c15e0a853b'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2080070100-2080123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2080070100-2080123118.nc' 'SHA256' '01d60ed6be850996eba3fc3df9d8da9178a5ac81c3357166140b61b03ee8721a'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2081010100-2081063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2081010100-2081063018.nc' 'SHA256' '922819004d7518ac8a1e1d1433e0c1738caa8010aef4db7331db139482d361ec'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2081070100-2081123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2081070100-2081123118.nc' 'SHA256' '903cb18a78b13b4c46a2cd3db3d1cb1084a58f383e4160cdd2dc3625b3510e60'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2082010100-2082063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2082010100-2082063018.nc' 'SHA256' 'a83f096e1f99ec2c3162ed86927efc53cbc7891c90fe019d56e4b4198df76d59'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2082070100-2082123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2082070100-2082123118.nc' 'SHA256' '2161f5de837584aa53a92fbb92a53fc23124aacfa9eaf331b5308495c86e6e83'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2083010100-2083063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2083010100-2083063018.nc' 'SHA256' '0caf4b8f7c9c1c0531e342b2a0f8138e76711fb676502bd6758d512d20e92972'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2083070100-2083123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2083070100-2083123118.nc' 'SHA256' 'e3e15ea4b5f4a1488dac2a5af45bbd305dc4102ab1579a2a4ea35b37a0a8d91d'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2084010100-2084063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2084010100-2084063018.nc' 'SHA256' '6541297ec09d0427609d3750b599a9f440142470c812f5a81c50335aae50eccc'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2084070100-2084123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2084070100-2084123118.nc' 'SHA256' '29a36cc2ece5e9104262659cb2db4b4e6d70f8497fd316f5c9476fc2a71783cf'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2085010100-2085063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2085010100-2085063018.nc' 'SHA256' 'e4d853273b35b0cd3136245cce51db1e5f36276f4d4b350143d3c7f51b23aed9'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2085070100-2085123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2085070100-2085123118.nc' 'SHA256' '8741e5940aeb82081fd600f325aa0319aa3e9dfdbff3b0b86a2f10979eac1902'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2086010100-2086063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2086010100-2086063018.nc' 'SHA256' '2eabddeaa4a23df0bbd20076c02b9214a6705ac3d02fa3d90b81368c984a4889'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2086070100-2086123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2086070100-2086123118.nc' 'SHA256' '63911f34102f8fe04df98aea4c961d5cfd00c81f698b5ba14c32c8ed7a238bfb'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2087010100-2087063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2087010100-2087063018.nc' 'SHA256' '82b24bf746d40e6c25f449993ac6ef2adb09060619f90697dc92c173af97d6f4'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2087070100-2087123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2087070100-2087123118.nc' 'SHA256' 'a263e42d338b834a89961f14688300f6f5fdd361c5033ef06af6014d00c73374'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2088010100-2088063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2088010100-2088063018.nc' 'SHA256' '8762eb35bec1e931e38d226cc10e7f628600b23398dea5c460ff8b75f39d277e'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2088070100-2088123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2088070100-2088123118.nc' 'SHA256' '479461c0f33a482bcc254a22dc639dfdff70c891f2681cb9008f2bc6e9e455f6'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2089010100-2089063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2089010100-2089063018.nc' 'SHA256' '28737669c6214cf5aa5a36eb65b41f57cd0fd1423a321472d75830783c0ba742'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2089070100-2089123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2089070100-2089123118.nc' 'SHA256' '25cc308af54cfc1b81686d726d6e161e001470108ff1981bc338d06b744afa8b'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2090010100-2090063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2090010100-2090063018.nc' 'SHA256' '90d560640526e058231c29995fc71beadfe184cf1098ef3b21803b14a983b369'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2090070100-2090123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2090070100-2090123118.nc' 'SHA256' 'e953f8c2651851305ce2421867f487858cd8b49ce1f18282a49b8d6bded17e7f'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2091010100-2091063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2091010100-2091063018.nc' 'SHA256' 'c29bfc9301713e7e6c106e4dea9aaca431024210c9e65ad9ae2dc006df16fdaf'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2091070100-2091123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2091070100-2091123118.nc' 'SHA256' '0bc5489335489c1a62c051230ef3043229e89d5801f1eccb5b038c1151190f57'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2092010100-2092063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2092010100-2092063018.nc' 'SHA256' '57614ed23eb0cf0d92d2e60d3b36fb2bd7f4e468b15060f31851729f184e8be2'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2092070100-2092123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2092070100-2092123118.nc' 'SHA256' '89c89eabef620451e946f9a32d155a7f418ce3a0c630d592a7c4f4159f69f54e'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2093010100-2093063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2093010100-2093063018.nc' 'SHA256' '03e1205a881200ed2cde15dfcf7c061caca643b4aaeaf8065e11b87ece0ce093'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2093070100-2093123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2093070100-2093123118.nc' 'SHA256' '02196a96ce37f1bd2ed94b6230868742f0ad6b27b0045f5ed81bf6f3a0255b1c'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2094010100-2094063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2094010100-2094063018.nc' 'SHA256' 'e8163e3927e2ef3860543e8af695b90249d19217c865baabe209bc4c5c7ff180'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2094070100-2094123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2094070100-2094123118.nc' 'SHA256' '34186fc5015b706e14ec41efac8fcf3c907e5eb58656dee093ac87dbd7440439'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2095010100-2095063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2095010100-2095063018.nc' 'SHA256' '0fb3d64bed5fd8f32f555870e619a33db977b086ed3d94172dd75bcff95f8238'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2095070100-2095123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2095070100-2095123118.nc' 'SHA256' '8e5e26eb02fc3bd590c5431df44f71c71fa09499b7a495ee1966ef8203ed1cfd'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2096010100-2096063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2096010100-2096063018.nc' 'SHA256' 'e8cd7eb1b7f73d1a8ea0834fc57dd3f7002ee88b2ae369f598a5bdff3d5c444e'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2096070100-2096123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2096070100-2096123118.nc' 'SHA256' 'f2a4352ad53674de3811855b809b5a7db1e2519ec3ce294f602dd027e7259ec7'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2097010100-2097063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2097010100-2097063018.nc' 'SHA256' 'b70008dfba538ab76783fa598490ebdb39ed666651c2eb00adf5aafa8fc8a511'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2097070100-2097123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2097070100-2097123118.nc' 'SHA256' '6aca71d7d71a1a4916a61d0eec8298e618497671ef4c7fab79707b44cf339b13'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2098010100-2098063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2098010100-2098063018.nc' 'SHA256' 'd2603607d161068e6a1181ad32ef3613208acf0927b9d6759a92b23bb48abefa'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2098070100-2098123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2098070100-2098123118.nc' 'SHA256' '26054fd245a668cb50024ec4e25d43c65babe748b019b36b10ea6c4483f05fe0'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2099010100-2099063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2099010100-2099063018.nc' 'SHA256' '92af3648bb5372bf5fda85558e7321b82721d92910eba98641a7f0d459c378cc'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2099070100-2099123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2099070100-2099123118.nc' 'SHA256' 'ccf31a51e011b8ab6a8479ad0427fab7864a86fb814935b264f6baa04eb72a2d'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2100010100-2100063018.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2100010100-2100063018.nc' 'SHA256' 'f9da78f4a1635bc9f32620bc6aa4a2b62c7ff9b1de3835e09c5b1a9e0c399dc9'
'va_6hrLev_NorESM1-M_rcp26_r1i1p1_2100070100-2100123118.nc' 'http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/output1/NCC/NorESM1-M/rcp26/6hr/atmos/6hrLev/r1i1p1/v20110901/va/va_6hrLev_NorESM1-M_rcp26_r1i1p1_2100070100-2100123118.nc' 'SHA256' '628b80d2a475b28ab7d0d6a28486c402586d93442939dca663e3392104496ead'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 770 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
